kind = "web"
previewPath = "/"
title = "RepSolana"
version = "1.0.0"
id = "artifacts/rep-solana"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22024

[services.development]
run = "pnpm --filter @workspace/rep-solana run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/rep-solana", "run", "build" ]
publicDir = "artifacts/rep-solana/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22024"
BASE_PATH = "/"
