/**
 * Off-chain metadata builder for the Bubblegum V2 cNFT `uri` field.
 *
 * Metadata strategy — self-hosted Vercel API route (no external service):
 *
 *   The cNFT metadata URI points to our own `/api/meta` serverless
 *   function. That endpoint generates the Metaplex-compatible JSON on the
 *   fly from the query params baked into the URL at mint time.
 *
 *   Why this replaces jsonblob.com:
 *     1. jsonblob POST — the Location header is not CORS-exposed, so
 *        res.headers.get('Location') always returns null in a browser.
 *        The upload succeeds server-side but the URL is unreadable to JS,
 *        so every mint fell back to the SPA HTML URL (Helius sees HTML,
 *        not JSON → blank NFT in wallet).
 *     2. jsonblob PUT — returns 404 for new UUIDs; it only updates
 *        existing blobs, not creates them. My PR #14 fix was also broken.
 *     3. Any external service adds a failure point and rate limits.
 *
 *   The self-hosted Vercel function is stateless, zero-dependency,
 *   always-on as long as Vercel is running, and returns application/json
 *   with the correct Content-Type instantly.
 *
 * Image strategy:
 *   The cNFT `image` field points to the single static collection image
 *   (`/passport.png`) hosted on Vercel. Every holder sees the same unified
 *   passport visual in their wallet (Phantom, Backpack, etc.).
 *   Per-holder richness — score, tier, badges — lives in `attributes`
 *   and in the app's public profile page (/p/<address>). The inline SVG
 *   generated by `passportImageDataUri` is still used for the in-app
 *   PassportCard UI; it is NOT baked into on-chain metadata.
 */

import type { ReputationProfile } from "./solana";
import { scoreTier } from "./passport";

export interface OnChainMetadataAttribute {
  trait_type: string;
  value: string | number;
}

export interface OnChainPassportMetadata {
  name: string;
  symbol: string;
  description: string;
  image: string;
  external_url: string;
  attributes: OnChainMetadataAttribute[];
  properties: {
    category: "image";
    creators: { address: string; share: number }[];
    files: { uri: string; type: string }[];
  };
  // Custom — RepSolana-specific verifiable claim block.
  repsolana: {
    version: "2.0";
    standard: "metaplex-bubblegum-v2-soulbound";
    address: string;
    score: number;
    tier: string;
    badges: string[];
    breakdown: { label: string; value: number; max: number; detail: string }[];
    activitySummary: {
      walletAgeDays: number;
      totalTxs: number;
      successRate: number;
      defi: number;
      staking: number;
      nft: number;
      uniqueProgramCount: number;
      solBalance: number;
    };
    issuedAt: number;
    soulbound: true;
    collectionMint: string;
    merkleTree: string;
  };
}

export function buildOnChainMetadata(
  profile: ReputationProfile,
  ctx: { collectionMint: string; merkleTree: string },
): OnChainPassportMetadata {
  const tier = scoreTier(profile.score.total).label;
  const earnedBadges = profile.badges.filter((b) => b.earned).map((b) => b.label);
  const successRate =
    profile.stats.totalTxs > 0
      ? profile.stats.successTxs / profile.stats.totalTxs
      : 0;

  const origin =
    typeof window !== "undefined"
      ? window.location.origin
      : "https://rep-solana.vercel.app";
  const imageUrl = `${origin}/passport.png`;

  // Solana's MetadataArgsV2.name has a HARD 32-byte limit. Anything
  // longer is silently truncated by the SDK, and that truncated form is
  // what the leaf hash commits to ON-CHAIN forever. Keep the score early
  // in the name so it never gets clipped.
  //
  // Format: "RepSolana #100 · Legendary" = 26 bytes (worst case, fits)
  const onChainName = `RepSolana #${profile.score.total} · ${tier}`;

  return {
    name: onChainName,
    symbol: "REPSOL",
    description:
      "Soulbound, compressed reputation passport on Solana. " +
      "Score, badges and activity claims are derived live from on-chain " +
      "history at mint time. Non-transferable: enforced via Metaplex " +
      "Bubblegum V2 + Core PermanentFreezeDelegate.",
    image: imageUrl,
    external_url: `${origin}/p/${profile.address}`,
    attributes: [
      { trait_type: "Score", value: profile.score.total },
      { trait_type: "Tier", value: tier },
      { trait_type: "Wallet Age (days)", value: Math.round(profile.stats.walletAgeDays) },
      { trait_type: "Total Txs", value: profile.stats.totalTxs },
      { trait_type: "Success Rate", value: `${(successRate * 100).toFixed(0)}%` },
      { trait_type: "DeFi Interactions", value: profile.stats.categoryCounts.defi },
      { trait_type: "Staking Actions", value: profile.stats.categoryCounts.staking },
      { trait_type: "NFT Interactions", value: profile.stats.categoryCounts.nft },
      { trait_type: "Unique Programs", value: profile.stats.uniqueProgramCount },
      { trait_type: "Soulbound", value: "true" },
      { trait_type: "Standard", value: "Bubblegum V2" },
      ...earnedBadges.map((b) => ({ trait_type: "Badge", value: b })),
    ],
    properties: {
      category: "image",
      creators: [{ address: profile.address, share: 100 }],
      files: [{ uri: imageUrl, type: "image/png" }],
    },
    repsolana: {
      version: "2.0",
      standard: "metaplex-bubblegum-v2-soulbound",
      address: profile.address,
      score: profile.score.total,
      tier,
      badges: earnedBadges,
      breakdown: profile.score.components.map((c) => ({
        label: c.label,
        value: c.value,
        max: c.max,
        detail: c.detail,
      })),
      activitySummary: {
        walletAgeDays: Math.round(profile.stats.walletAgeDays),
        totalTxs: profile.stats.totalTxs,
        successRate,
        defi: profile.stats.categoryCounts.defi,
        staking: profile.stats.categoryCounts.staking,
        nft: profile.stats.categoryCounts.nft,
        uniqueProgramCount: profile.stats.uniqueProgramCount,
        solBalance: profile.stats.solBalance,
      },
      issuedAt: Date.now(),
      soulbound: true,
      collectionMint: ctx.collectionMint,
      merkleTree: ctx.merkleTree,
    },
  };
}

/**
 * Build the metadata URI to bake into the cNFT leaf.
 *
 * Points to our self-hosted Vercel serverless function `/api/meta` which
 * generates the Metaplex-compatible JSON on the fly from score + tier
 * encoded in the URL. No upload, no external service, no CORS issues.
 *
 * URL format: https://<origin>/api/meta?a=<address>&s=<score>&t=<tier>
 * Worst-case length (~110 chars) is well within the 200-byte URI limit.
 *
 * Kept async to match the existing call-site signature in bubblegum.ts
 * (no await cost — resolves immediately).
 */
export async function uploadMetadataJSON(
  metadata: OnChainPassportMetadata,
): Promise<string> {
  const origin =
    typeof window !== "undefined"
      ? window.location.origin
      : "https://rep-solana.vercel.app";
  const params = new URLSearchParams({
    a: metadata.repsolana.address,
    s: String(metadata.repsolana.score),
    t: metadata.repsolana.tier,
  });
  // Slice to 200 as a safety net; in practice this URL is ~110 chars max.
  return `${origin}/api/meta?${params.toString()}`.slice(0, 200);
}
